require_relative "../database_class_methods.rb"
require_relative "../database_instance_methods.rb"

class Ride
  extend DatabaseClassMethods
  include DatabaseInstanceMethods
  

  attr_accessor :cyclist_id, :bike_id, :ride_name, :miles, :period
  attr_reader :id

  # Initializes a new Bike object
  #
  # id         - Integer id primary key created in the 'bikes' table
  # cyclist_id - Integer containing the id of the cyclist who owns the bike
  # bike_id    - Integer containing the id of the bike used on the ride
  # ride_name  - (optional) String containing the name of the ride
  # miles      - Integer containing the number of miles ridden
  # period   - date time value generated by the database
  #
  # Returns a Bike object
  
  def initialize(options = {})
    
    # Example: {"id" => 1, "cyclist_id" => "3", "bike_id" => "2", "ride_name" => "Keystone trail", "miles" => "10.7", "period" => "date/time" }
    @id = options["id"]
    @cyclist_id = options["cyclist_id"]
    @bike_id = options["bike_id"]
    @ride_name = options["ride_name"]
    @miles = options["miles"]
    @period = options["period"]
 
  end
  
  # method to validate rides before they are added to the database
  #
  # cyclist_id - Integer containing the cyclist id of the bike's owner
  # bike_id    - Integer containing the id of the bike ridden
  # miles      - Integer containing the distance ridden
  #
  # Returns boolean
  def self.valid?(cyclist_id, bike_id, miles)
    if cyclist_id.empty? || bike_id.empty? || miles.empty?
      true
    end
  end
end